steps:
  build-controle:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: "${CI_COMMIT_TAG##v}-controle"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: tag
    ref: refs/tags/v*